#!/bin/sh
# $1: filename; $2: timeout (mins)
SUBMISSION=$(basename ${1})
SUBMISSIONBASE=${SUBMISSION%.[rR][mM][dD]}

cp "${1}" ../build-dir; cd ../build-dir
timeout -v ${2}m Rscript --vanilla -e "rmarkdown::render('${SUBMISSION}', rmarkdown::html_document())" \
	>/dev/null 2>../logs/"${SUBMISSIONBASE}".log &&\
 	(echo success
	rm -f ../logs/"${SUBMISSIONBASE}".log
 	mv "${SUBMISSIONBASE}".html ../output/
 	mv "${1}" ../submissions/"${SUBMISSIONBASE}".buildsuccess
	find . ! -name 'covid-*.csv' -delete) ||\
 	(echo failure
 	mv "${1}" ../submissions/"${SUBMISSIONBASE}".buildfailure
	find . ! -name 'covid-*.csv' -delete)
