#!/bin/sh

RS='\036'
US='\035'
SUBMISSION=`basename "$1"`
SUBMISSIONBASE=${SUBMISSION%.buildsuccess}

qutebrowser ../output/$SUBMISSIONBASE.html 2>/dev/null &
echo -n "Comments: "
read comment
echo -n "Grade: "
read grade

printf "${SUBMISSIONBASE}${US}${grade}${US}${comment}${RS}" >>../marks

mv "$1" ../submissions/"${SUBMISSIONBASE}".marked
