#!/bin/sh

unzip ../submissions.zip -d ../unpack-subs
find ../unpack-subs -name '*.tar.gz' -execdir tar -xzf {} \;
rename 'y/ /_/;y/A-Z/a-z/;s/_.*/.rmd/' `find ../unpack-subs -name '*.[Rr]md'`
find ../unpack-subs -name '*.rmd' -exec mv {} ../submissions \;
